cicd: Clone with SSH

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -224,19 +224,29 @@ jobs:
       - name: 🗓 Get AIRAC
         run: |
           echo "AIRAC_DATE=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//_/g')" >> $GITHUB_ENV
-          echo "AIRAC_SHORT=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//_/g' | sed 's/20\([0-9][0-9]\)_\([0-9][0-9]\)/\1\2/g')" >> $GITHUB_ENV
+          echo "AIRAC_SHORT=$(echo ${GITHUB_REF#refs/*/} | sed 's/\//_/g' | sed -E 's/20([0-9]{2})_([0-9]{2}[a-zA-Z]*)/\1\2/')" >> $GITHUB_ENV
 
       - name: 🗂 Setup Git
         run: |
-          git config --local user.email "privileged-access@vatsim.uk"
-          git config --local user.name "VATSIM UK"
+          git config --global user.email "privileged-access@vatsim.uk"
+          git config --global user.name "VATSIM UK"
 
       - name: 📂 [DOCS] Clone Documentation Repo
-        env:
-          TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "📂 Cloning Docs Website"
-          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VATSIM-UK/atc-documentation.git atc-documentation || {
+          echo "💻 Starting SSH agent"
+          eval "$(ssh-agent -s)"
+          ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+
+          echo "🔃 Loaded SSH Keys:"
+          ssh-add -l || echo "❌ No SSH keys loaded"
+
+          echo "🐞 Testing SSH connection to GitHub"
+          ssh -T git@github.com || echo "❌ SSH auth to GitHub failed!"
+
+          echo "📥 Cloning Docs Website"
+          git clone git@github.com:VATSIM-UK/atc-documentation.git atc-documentation || {
             echo "❌ Failed to clone documentation repo"; exit 1;
           }
 
@@ -277,6 +287,13 @@ jobs:
 
       - name: 📆 [DOCS] Commit Changes
         run: |
+          echo "💻 Starting SSH agent"
+          eval "$(ssh-agent -s)"
+          ssh-add - <<< "${{ secrets.DOCS_DEPLOY_KEY }}"
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts    
+
           cd atc-documentation
-          git commit -am "Upload Controller Pack ${AIRAC_DATE}"
+          git add .
+          git commit -m "Upload Controller Pack ${AIRAC_DATE}"
           git push origin uk-controller-pack
